# docker-compose -f docker-compose.yml up -d
version: '3.8'
services:
  mcp-server-csdn:
    image: registry.cn-wulanchabu.aliyuncs.com/wanyj-mcp/mcp-server-csdn:1.0
    container_name: mcp-server-csdn
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - ./log:/data/log
    environment:
      - TZ=PRC
      - SERVER_PORT=9001
      - CSDN_API_CATEGORIES=Java场景面试宝典
      - CSDN_API_COOKIE=uuid_tt_dd=10_19042643540-1734959090601-191983; fid=20_39117422500-1734959092324-311661; p_uid=U010000; c_ins_prid=-; c_ins_rid=1743861173539_159807; c_ins_fref=https://blog.csdn.net/nener_give_up; c_ins_fpage=/index.html; c_ins_um=-; ins_first_time=1743861178470; ssxmod_itna=eqjx0DuDRDg00=DCQDXDnQAwvPWuM7+EkDh3+rqGXht3DZDiqAPGhDC+898+b2ir5qrzAbAE=K3t0DhpNWf4aeaKffhDPDHxY=DU6Gb7Dx1q0rD74irDDxD3DbRdDSDWKD9D04kg9XMKDEDYP9DA3Di4D+7uQDmqG0DDU7B4G2D7UyQDDlQ0TqKT+YYQrU8jU3vqhe57D9D0UdxBLtmcD9+C98=7XeH6axa2QDzk7DtMUSBuL3x0pySqNxZ24aW043fihYAAqFi7DWjYx40UpYighbi0mGSY+tYYCKR3w3j5DAiNk=eD; ssxmod_itna2=eqjx0DuDRDg00=DCQDXDnQAwvPWuM7+EkDh3+xA6nt+YD/WQ+DFrUwUP9GKAPlxKzckGNC3KFjH6xqKf0Hi8qjQmiWIezSLFv6dvSj5W0N/Ful7jTOmn5q86oK6BDmlYRLnHPH5DkUzU85w+u6sA2Qlj7fMlxfxl4NYsOb8YW690LYeWQfdLlTPf8uE0jtNvqx7G+57WfY6GcKh8cn7ArXTx6Yz8k9=41UYclu1VMpOridd2e3DxKhqhffDLTSDhbdLTlpp6r3N+DKKcwDEsYHqLr=fzxteL+1VGh1BQMfzGL3RGudRb5nep1tWrDm6tBw4qsSKziDA3a2Rm03+eLYP6hHWqNSqKTB0jAhWuCe7NzACzA8/YWmqO7gibow9woZxw9KO025Ngi7WN7WdZ2GK4tDwMlgkArcY3CmT/m+3D074xDLxD2QGDD===; tfstk=gFSKVk0Dp5VnhhK0xkairb6SE_2gIgBF16WjqQAnP1COw1OhtTNeNLC9sUbHZHGS26XCKUqEACg6UpdSA0tB2U6V9MxuLH9-2t5RK3AHAhO6hKoSVeOI5vSOM0m3TyWS23x7iSq0m9W943Nm_RwzXBJPCQwMR1WQQzK7iSqMFSs0h31kyUtSBOOweLiBF_O6fCJjP3OBPfg6hCOWV_TW5F9H32gIVLT_BLR6N3t5NOGAI8AszQiRupjnTGi2S0i5XpL_S9O_RsS9ppAfdGoSVx9pJI6B6WNcQIT1UUIrU0LfdZ5yh6GQwQSOCM_fG50HOZpRnaBQActhY9_XPiNrPsKdwEsBWYwRK3dJXdsbEqRGXBf5vFwmDUx1mEtCSPPHrHpANM5Ke01fItje7gFx1Q7H3h9R4-gJwUsPEijY_gcDML0QBR3rze9aMSvP8xyjKXv9iJUoz48gldd0BR3rze9wBI2GD4uySr1..; c_dl_prid=-; c_dl_rid=1745760964418_110363; c_dl_fref=https://blog.csdn.net/qqisme777/article/details/138317841; c_dl_fpage=/; c_dl_um=distribute.pc_search_result.none-task-blog-2%7Eall%7Esobaiduweb%7Edefault-1-138317841.142%5Ev100%5Epc_search_result_base3; dc_session_id=10_1753440511860.699195; c_segment=15; dc_sid=9d99c413284e81d2cacf8f7304265aee; Hm_lvt_6bcd52f51e9b3dce32bec4a3997715ac=1753440512; HMACCOUNT=0FBC2AFEF2F4CA9D; _clck=1d1b6ea%7C2%7Cfxw%7C0%7C1921; creative_btn_mp=1; hide_login=1; UserName=2401_86434325; UserInfo=619fd60a072742b59c216ff493099732; UserToken=619fd60a072742b59c216ff493099732; UserNick=2401_86434325; AU=CD4; UN=2401_86434325; BT=1753440569430; csdn_newcert_2401_86434325=1; __gads=ID=f2145097b73a3528:T=1734959092:RT=1753440910:S=ALNI_MZoXX8RKCiboNTfWQqXRHydoi4ZVA; __gpi=UID=00000fb4dce4bb79:T=1734959092:RT=1753440910:S=ALNI_MZS5B2zulb6PhGJLXcQqER5pPDv9g; __eoi=ID=b84b5a6b76971566:T=1753440514:RT=1753440910:S=AA-AfjaziAnagfcEkoSXBt1HjzUX; _clsk=1r76882%7C1753444142359%7C7%7C0%7Cq.clarity.ms%2Fcollect; SESSION=fdcc350a-98d8-40ec-a435-84d35f676b87; c_first_ref=github.com; c_first_page=https%3A//i.csdn.net/bind.html%3Ftype%3Dgithub%26msg%3D6%26result%3Dtrue; c_dsid=11_1753445026665.532943; Hm_lpvt_6bcd52f51e9b3dce32bec4a3997715ac=1753445036; c_pref=https%3A//i.csdn.net/; c_ref=https%3A//mp.csdn.net/; c_page_id=default; log_Id_pv=30; creativeSetApiNew=%7B%22toolbarImg%22%3A%22https%3A//img-home.csdnimg.cn/images/20231011044944.png%22%2C%22publishSuccessImg%22%3A%22https%3A//img-home.csdnimg.cn/images/20240229024608.png%22%2C%22articleNum%22%3A0%2C%22type%22%3A0%2C%22oldUser%22%3Afalse%2C%22useSeven%22%3Atrue%2C%22oldFullVersion%22%3Afalse%2C%22userName%22%3A%222401_86434325%22%7D; log_Id_view=289; dc_tos=szyevc; log_Id_click=35
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network

  mcp-server-weixin:
    image: registry.cn-wulanchabu.aliyuncs.com/wanyj-mcp/mcp-server-weixin:1.0
    container_name: mcp-server-weixin
    restart: always
    ports:
      - "9004:9004"
    volumes:
      - ./log:/data/log
    environment:
      - TZ=PRC
      - SERVER_PORT=9004
      - WEIXIN_API_ORIGINAL_ID=gh_10d5159bf95d
      - WEIXIN_API_APP_ID=wx9b28ce6be5b15db0
      - WEIXIN_API_APP_SECRET=5a2aee20e1ad92516c688c6d04d595b4
      - WEIXIN_API_TEMPLATE_ID=4Jil4eEhYnqTR7ZAZ7S2U-iQEmFBu5P-kW2FYqiiuOQ
      - WEIXIN_API_TOUSER=ovtZM7LYJgaSuN40qctFUR0WYBEo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
