spring:
  application:
    name: mcp-server-weixin
  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: 1.0.0
        stdio: true
  main:
    banner-mode: off
    web-application-type: none

logging:
  pattern:
    console:
  file:
    name: data/mcp-log/${spring.application.name}.log

weixin:
  api:
    original_id:
    app-id:
    app-secret:
    template_id:
    touser:

